// bindings.rs — AUTO-GENERATED by WIDL compiler
// DO NOT EDIT manually.
// Run: widlc weilguard.widl --lang rust --out src/bindings.rs

use serde::{Deserialize, Serialize};
use weil_macros::{constructor, mutate, query, smart_contract, WeilType};

pub trait WeilGuard {
    fn new() -> Result<Self, String>
    where
        Self: Sized;

    // mutate methods — modify on-chain state
    async fn register_agent(
        &mut self,
        agent_id: String,
        policy_json: String,
    ) -> Result<String, String>;

    async fn log_event(
        &mut self,
        agent_id: String,
        action: String,
        payload: String,
    ) -> Result<String, String>;

    async fn flag_violation(
        &mut self,
        agent_id: String,
        reason: String,
        severity: String,
    ) -> Result<String, String>;

    async fn revoke_agent(
        &mut self,
        agent_id: String,
        reason: String,
    ) -> Result<bool, String>;

    async fn update_policy(
        &mut self,
        agent_id: String,
        new_policy_json: String,
    ) -> Result<bool, String>;

    // query methods — read-only, no state change
    async fn check_policy(&self, agent_id: String, proposed_action: String) -> String;
    async fn get_audit_log(&self, agent_id: String) -> String;
    async fn get_violations(&self, agent_id: String) -> String;
    async fn compliance_score(&self, agent_id: String) -> u32;
}

#[derive(Serialize, Deserialize, WeilType, Clone)]
pub struct AgentRecord {
    pub agent_id:    String,
    pub policy_json: String,
    pub active:      bool,
    pub registered_at: u64,
}

#[derive(Serialize, Deserialize, WeilType, Clone)]
pub struct AuditEvent {
    pub event_id:   String,  // sha256 hash
    pub agent_id:   String,
    pub action:     String,
    pub payload:    String,
    pub timestamp:  u64,
}

#[derive(Serialize, Deserialize, WeilType, Clone)]
pub struct Violation {
    pub violation_id: String,
    pub agent_id:     String,
    pub reason:       String,
    pub severity:     String,  // "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"
    pub timestamp:    u64,
}

#[derive(Serialize, Deserialize, WeilType)]
pub struct WeilGuardContractState {
    // Stores agent_id → AgentRecord
    pub agents:     weil_sdk::collections::WeilMap<String, AgentRecord>,
    // Stores agent_id → list of AuditEvents (serialised as JSON string per agent)
    pub audit_logs: weil_sdk::collections::WeilMap<String, String>,
    // Stores agent_id → list of Violations (serialised as JSON string per agent)
    pub violations: weil_sdk::collections::WeilMap<String, String>,
}
